#!/usr/bin/env python3
"""Check that every repository path the instructions name still exists.

Separate from test_guards.py because it needs a clone of the samples repository, which
the image does not contain. Run it with a path:

    python tests/test_repo_references.py /app/work/sample-per-model-bedrock

It exists because two instructions in these skills were wrong when written: they told the
agent to run `verify-all.sh` and to add a `.secrets.baseline` entry, and neither file is in
the public repository -- both live in a separate private one. A wrong instruction of that
shape does not fail loudly. The agent looks for the file, does not find it, and either
wastes turns or quietly skips a step it was told to take.

Paths are scraped from the markdown and resolved against the clone, so the instruction and
the repository are two independent sources. Exit 0 means every path resolves.

This sets a writing convention for the skills, which is what makes the check mechanical
rather than a heuristic: **a path in backticks is a path the agent must be able to open.**
If you need to mention a file that is deliberately absent, write its name as prose without
backticks. Otherwise this check cannot tell "open this" from "this does not exist", and
the first thing it flagged was a sentence saying a file was missing.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent

# Things that look like paths but are not paths in the samples repository: files the agent
# creates, files belonging to this container, and generic filenames used as examples.
NOT_REPO_PATHS = {
    "requirements.txt",          # exists, but also names this container's own file
    "SKILL.md",
    "system_prompt.md",
    "tests/test_repo_references.py",
    "tests/test_guards.py",
}

PATTERN = re.compile(
    r"`("
    r"[A-Za-z0-9_./-]+\.(?:py|ipynb|sh|md|txt|baseline)"   # a filename with an extension
    r"|[0-9]{2}-[a-z-]+/[0-9]{2}[A-Za-z0-9_.-]*"           # e.g. 00-foundations/04
    r"|_shared/[A-Za-z0-9_.]+"                             # the shared helper directory
    r")`"
)


def sources() -> list[Path]:
    docs = sorted((HERE / ".claude" / "skills").glob("*/SKILL.md"))
    docs.append(HERE / "agent" / "system_prompt.md")
    return [d for d in docs if d.exists()]


def tracked_files(repo: Path) -> set[str]:
    """What git actually carries, which is what a clone will contain.

    Not the filesystem. A notebook can write files when executed, and caches and
    gitignored artefacts appear in a working tree that no clone has. Resolving against
    the filesystem would let a skill instruction naming such a file pass this check,
    while the agent working from a fresh clone could never find it.
    """
    out = subprocess.run(  # noqa: S603
        ["git", "-C", str(repo), "ls-files"],
        capture_output=True, text=True, check=False,
    )
    if out.returncode != 0:
        raise SystemExit(
            f"{repo} is not a git repository, so what a clone contains cannot be "
            "determined. Point this at a clone, not at an export."
        )
    return {line.strip() for line in out.stdout.splitlines() if line.strip()}


def resolves(tracked: set[str], path: str) -> bool:
    if path in tracked:
        return True
    # `00-foundations/04` is a prefix: notebooks carry a title after the number.
    if "/" in path and any(t.startswith(path) for t in tracked):
        return True
    # A bare filename may live anywhere in the tree.
    return "/" not in path and any(t.rsplit("/", 1)[-1] == path for t in tracked)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__.strip().splitlines()[0])
        print(f"usage: {Path(argv[0]).name} <path-to-samples-clone>")
        return 2
    repo = Path(argv[1]).resolve()
    if not (repo / "README.md").exists():
        print(f"{repo} does not look like the samples repository (no README.md)")
        return 2

    tracked = tracked_files(repo)
    notebooks = len([t for t in tracked if t.endswith(".ipynb")])
    untracked_py = len([p for p in repo.rglob("*.py")
                        if ".git" not in p.parts
                        and str(p.relative_to(repo)) not in tracked])
    print(f"checking instructions against {repo}")
    print(f"  {len(tracked)} tracked file(s), {notebooks} notebook(s)")
    if untracked_py:
        print(f"  ignoring {untracked_py} untracked .py file(s) -- generated by running "
              "notebooks, and absent from any clone")

    found: dict[str, set[str]] = {}
    for doc in sources():
        label = doc.parent.name if doc.name == "SKILL.md" else doc.name
        for path in PATTERN.findall(doc.read_text()):
            if path not in NOT_REPO_PATHS:
                found.setdefault(path, set()).add(label)

    missing: list[str] = []
    for path, where in sorted(found.items()):
        ok = resolves(tracked, path)
        print(f"  {'ok     ' if ok else 'MISSING'} {path:56} {sorted(where)}")
        if not ok:
            missing.append(f"{path} (named in {sorted(where)})")

    if missing:
        print(f"\n{len(missing)} path(s) named in the instructions do not exist:")
        for m in missing:
            print(f"  - {m}")
        print(
            "\nThe instruction is stale, not the repository. Either the file moved, it "
            "never existed, or it is generated at runtime and gitignored so no clone has "
            "it. Fix the skill; do not create the file to make this pass."
        )
        return 1
    print(f"\nall {len(found)} referenced path(s) resolve")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
